### ISSUE TITLE
上传文件夹名称如果包含+号，会出现文件夹剪切不到process，系统出现重复数据。

### ISSUE THREAD

**Issue by HP-TimmyZheng** [hydraadmin/HuCaiBookProcess#204]
。-已通知业务部门是未按标准操作导致。待改进。

**Comment by hpjinjiang** [comment]
@tuqing，扫描员扫描完成书本文件夹的命名规则：文件夹命名只支持字母,数字，中英文，英文下划线，其它不支持，例如空格，特殊字符。
不符合此规则的文件夹禁止上传。
