### ISSUE TITLE
11月6日书《春夏钩针编制实例-1》卡在装订中，问题无法在虎彩和内网重现。

### ISSUE THREAD

**Issue by HP-TimmyZheng** [hydraadmin/HuCaiBookProcess#205]
•Rootcause: .NET发起新任务请求，而对该bookID可能JAVAAPI返回多条jobID记录中比较旧的一条，因而出现状态跟jobID不匹配导致状态更新失败。
•修改JAVA接口API的查寻，通过request URL+ BookID+ Status返回对应的jobID

**Comment by HP-TimmyZheng** [comment]
Assign给Kezhen进行生产环境部署。

**Comment by hpjinjiang** [comment]
针对卡在装订中的问题，已在客户现场环境进行了相应的修复，试运行一个月未再出现无故卡在装订中现象。
